# Generated by Django 4.0.6 on 2022-07-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_competition', models.CharField(max_length=255)),
                ('place_competition', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_athlete', models.CharField(max_length=255)),
                ('age_athlete', models.CharField(max_length=25)),
                ('height_athlete', models.CharField(max_length=25)),
                ('weight_athlete', models.CharField(max_length=25)),
            ],
        ),
    ]
